<?php

namespace ContainerVugIyxn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OLLeE3uService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oLLeE3u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oLLeE3u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\BilletController::delete' => ['privates', '.service_locator.1XeBFJ0', 'get_ServiceLocator_1XeBFJ0Service', true],
            'App\\Controller\\BilletController::edit' => ['privates', '.service_locator.1XeBFJ0', 'get_ServiceLocator_1XeBFJ0Service', true],
            'App\\Controller\\BilletController::index' => ['privates', '.service_locator.0c77nnS', 'get_ServiceLocator_0c77nnSService', true],
            'App\\Controller\\BilletController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\BilletController::show' => ['privates', '.service_locator.HCgIJYh', 'get_ServiceLocator_HCgIJYhService', true],
            'App\\Controller\\EvenementController::delete' => ['privates', '.service_locator.HuHdp3s', 'get_ServiceLocator_HuHdp3sService', true],
            'App\\Controller\\EvenementController::edit' => ['privates', '.service_locator.HuHdp3s', 'get_ServiceLocator_HuHdp3sService', true],
            'App\\Controller\\EvenementController::eventfront' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EvenementController::show' => ['privates', '.service_locator.td4zu.o', 'get_ServiceLocator_Td4zu_OService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BilletController:delete' => ['privates', '.service_locator.1XeBFJ0', 'get_ServiceLocator_1XeBFJ0Service', true],
            'App\\Controller\\BilletController:edit' => ['privates', '.service_locator.1XeBFJ0', 'get_ServiceLocator_1XeBFJ0Service', true],
            'App\\Controller\\BilletController:index' => ['privates', '.service_locator.0c77nnS', 'get_ServiceLocator_0c77nnSService', true],
            'App\\Controller\\BilletController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\BilletController:show' => ['privates', '.service_locator.HCgIJYh', 'get_ServiceLocator_HCgIJYhService', true],
            'App\\Controller\\EvenementController:delete' => ['privates', '.service_locator.HuHdp3s', 'get_ServiceLocator_HuHdp3sService', true],
            'App\\Controller\\EvenementController:edit' => ['privates', '.service_locator.HuHdp3s', 'get_ServiceLocator_HuHdp3sService', true],
            'App\\Controller\\EvenementController:eventfront' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.pX4JUuC', 'get_ServiceLocator_PX4JUuCService', true],
            'App\\Controller\\EvenementController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EvenementController:show' => ['privates', '.service_locator.td4zu.o', 'get_ServiceLocator_Td4zu_OService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BilletController::delete' => '?',
            'App\\Controller\\BilletController::edit' => '?',
            'App\\Controller\\BilletController::index' => '?',
            'App\\Controller\\BilletController::new' => '?',
            'App\\Controller\\BilletController::show' => '?',
            'App\\Controller\\EvenementController::delete' => '?',
            'App\\Controller\\EvenementController::edit' => '?',
            'App\\Controller\\EvenementController::eventfront' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::new' => '?',
            'App\\Controller\\EvenementController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BilletController:delete' => '?',
            'App\\Controller\\BilletController:edit' => '?',
            'App\\Controller\\BilletController:index' => '?',
            'App\\Controller\\BilletController:new' => '?',
            'App\\Controller\\BilletController:show' => '?',
            'App\\Controller\\EvenementController:delete' => '?',
            'App\\Controller\\EvenementController:edit' => '?',
            'App\\Controller\\EvenementController:eventfront' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:new' => '?',
            'App\\Controller\\EvenementController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
