<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9P6rjWxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9P6rjWx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9P6rjWx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'reservation' => ['privates', '.errored.bzbcrR6', NULL, 'Cannot determine controller argument for "App\\Controller\\ReservationController::delete()": the $reservation argument is type-hinted with the non-existent class or interface: "App\\Entity\\Reservation".'],
        ], [
            'entityManager' => '?',
            'reservation' => '?',
        ]);
    }
}
