<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZrpothfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zrpothf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zrpothf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transport' => ['privates', '.errored..service_locator.Zrpothf.App\\Entity\\Transport', NULL, 'Cannot autowire service ".service_locator.Zrpothf": it needs an instance of "App\\Entity\\Transport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'transport' => 'App\\Entity\\Transport',
        ]);
    }
}
