<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7COcd_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7C_Ocd.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7C_Ocd.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['privates', '.errored.CbSZfOQ', NULL, 'Cannot determine controller argument for "App\\Controller\\FrontHController::Hebergementavis()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'reservationRepository' => ['privates', '.errored.UXPr1RS', NULL, 'Cannot determine controller argument for "App\\Controller\\FrontHController::Hebergementavis()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ReservationRepository". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'reservationRepository' => '?',
        ]);
    }
}
