<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F7rY1ixService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F7rY1ix' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F7rY1ix'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Hebergement' => ['privates', '.errored..service_locator.F7rY1ix.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.F7rY1ix": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'Hebergement' => 'App\\Entity\\Hebergement',
            'entityManager' => '?',
        ]);
    }
}
