<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_BzbcrR6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.bzbcrR6' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ReservationController::delete()": the $reservation argument is type-hinted with the non-existent class or interface: "App\\Entity\\Reservation".');
    }
}
