<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_4TMHedDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.4TMHedD' shared service.
     *
     * @return \App\Repository\ReservationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ReservationController::index()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ReservationRepository".');
    }
}
