<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QnE6FuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._qnE6Fu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._qnE6Fu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ticketsRepository' => ['privates', 'App\\Repository\\TicketsRepository', 'getTicketsRepositoryService', true],
            'transport' => ['privates', '.errored..service_locator._qnE6Fu.App\\Entity\\Transport', NULL, 'Cannot autowire service ".service_locator._qnE6Fu": it needs an instance of "App\\Entity\\Transport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ticketsRepository' => 'App\\Repository\\TicketsRepository',
            'transport' => 'App\\Entity\\Transport',
        ]);
    }
}
