<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DsDs21Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DsDs2_1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DsDs2_1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', '.errored.soBjKwG', NULL, 'Cannot determine controller argument for "App\\Controller\\AvisController::index()": the $avisRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\AvisRepository".'],
        ], [
            'avisRepository' => '?',
        ]);
    }
}
