<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Xy7krWQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.xy7krWQ' shared service.
     *
     * @return \App\Entity\Avis
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AvisController::edit()": the $avi argument is type-hinted with the non-existent class or interface: "App\\Entity\\Avis".');
    }
}
