<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TfN0ld5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tfN0ld5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tfN0ld5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored.YxlUmlj', NULL, 'Cannot determine controller argument for "App\\Controller\\ReservationController::show()": the $reservation argument is type-hinted with the non-existent class or interface: "App\\Entity\\Reservation".'],
        ], [
            'reservation' => '?',
        ]);
    }
}
