<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MKb6udService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M_Kb6ud' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M_Kb6ud'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationRepository' => ['privates', '.errored.4TMHedD', NULL, 'Cannot determine controller argument for "App\\Controller\\ReservationController::index()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ReservationRepository".'],
        ], [
            'reservationRepository' => '?',
        ]);
    }
}
