<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HLm7Pv_.App\Entity\Hebergement' shared service.
     *
     * @return \App\Entity\Hebergement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HLm7Pv_": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded in "config/services.yaml".');
    }
}
