<?php

namespace ContainerMvady8Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicketsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K2ZqD6E.App\Entity\Tickets' shared service.
     *
     * @return \App\Entity\Tickets
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.K2ZqD6E": it needs an instance of "App\\Entity\\Tickets" but this type has been excluded in "config/services.yaml".');
    }
}
