<?php

namespace Container2csE2dE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ClAQttNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ClAQttN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ClAQttN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'hebergementRepository' => ['privates', '.errored.J609mEQ', NULL, 'Cannot determine controller argument for "App\\Controller\\AvisController::statistiques()": the $hebergementRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\HebergementRepository". Did you forget to add a use statement?'],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'hebergementRepository' => '?',
        ]);
    }
}
