<?php

namespace Container2csE2dE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CXZ2F6IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cXZ2F6I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cXZ2F6I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['privates', '.errored.vJSm82n', NULL, 'Cannot determine controller argument for "App\\Controller\\FrontHController::hebergementavis()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'reservationRepository' => ['privates', '.errored.6iiI.wC', NULL, 'Cannot determine controller argument for "App\\Controller\\FrontHController::hebergementavis()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ReservationRepository". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'reservationRepository' => '?',
        ]);
    }
}
