<?php

namespace Container2csE2dE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G9xr56rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g9xr56r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g9xr56r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hebergement' => ['privates', '.errored..service_locator.g9xr56r.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.g9xr56r": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'hebergement' => 'App\\Entity\\Hebergement',
        ]);
    }
}
