<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M9C2IMAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m9C2IMA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m9C2IMA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guideRepository' => ['privates', 'App\\Repository\\GuideRepository', 'getGuideRepositoryService', true],
        ], [
            'guideRepository' => 'App\\Repository\\GuideRepository',
        ]);
    }
}
