<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_19E7YVcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.19E7YVc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.19E7YVc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'transportRepository' => ['privates', 'App\\Repository\\TransportRepository', 'getTransportRepositoryService', true],
        ], [
            'paginator' => '?',
            'transportRepository' => 'App\\Repository\\TransportRepository',
        ]);
    }
}
