<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ISO_G2jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iSO.G2j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iSO.G2j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ticket' => ['privates', '.errored..service_locator.iSO.G2j.App\\Entity\\Tickets', NULL, 'Cannot autowire service ".service_locator.iSO.G2j": it needs an instance of "App\\Entity\\Tickets" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ticket' => 'App\\Entity\\Tickets',
        ]);
    }
}
