<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qo5PskpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qo5Pskp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qo5Pskp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'guide' => ['privates', '.errored..service_locator.Qo5Pskp.App\\Entity\\Guide', NULL, 'Cannot autowire service ".service_locator.Qo5Pskp": it needs an instance of "App\\Entity\\Guide" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'guide' => 'App\\Entity\\Guide',
        ]);
    }
}
