<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gp8L_PQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gp8L.PQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gp8L.PQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'excursion' => ['privates', '.errored..service_locator.gp8L.PQ.App\\Entity\\Excursion', NULL, 'Cannot autowire service ".service_locator.gp8L.PQ": it needs an instance of "App\\Entity\\Excursion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'excursion' => 'App\\Entity\\Excursion',
        ]);
    }
}
