<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SihDEo7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SihDEo7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SihDEo7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'BilletRepository' => ['privates', 'App\\Repository\\BilletRepository', 'getBilletRepositoryService', true],
            'Normalizer' => ['privates', '.errored.KqAv_DT', NULL, 'Cannot determine controller argument for "App\\Controller\\BilletController::searchbillet()": the $Normalizer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Serializer\\Normalizer\\NormalizerInterface".'],
        ], [
            'BilletRepository' => 'App\\Repository\\BilletRepository',
            'Normalizer' => '?',
        ]);
    }
}
