<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KqAvDTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.KqAv_DT' shared service.
     *
     * @return \Symfony\Component\Serializer\Normalizer\NormalizerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\BilletController::searchbillet()": the $Normalizer argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Serializer\\Normalizer\\NormalizerInterface".');
    }
}
