<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcursion2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gp8L.PQ.App\Entity\Excursion' shared service.
     *
     * @return \App\Entity\Excursion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gp8L.PQ": it needs an instance of "App\\Entity\\Excursion" but this type has been excluded in "config/services.yaml".');
    }
}
