<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F7rY1ix.App\Entity\Hebergement' shared service.
     *
     * @return \App\Entity\Hebergement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.F7rY1ix": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded in "config/services.yaml".');
    }
}
