<?php

namespace ContainerX2X3XfC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTickets2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iSO.G2j.App\Entity\Tickets' shared service.
     *
     * @return \App\Entity\Tickets
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iSO.G2j": it needs an instance of "App\\Entity\\Tickets" but this type has been excluded in "config/services.yaml".');
    }
}
