<?php

namespace ContainerMIBx7Ol;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VNXatTZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VNXatTZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VNXatTZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ProgrammeController::delete' => ['privates', '.service_locator.Xvt.gnO', 'get_ServiceLocator_Xvt_GnOService', true],
            'App\\Controller\\ProgrammeController::edit' => ['privates', '.service_locator.Xvt.gnO', 'get_ServiceLocator_Xvt_GnOService', true],
            'App\\Controller\\ProgrammeController::index' => ['privates', '.service_locator.n7FCdr5', 'get_ServiceLocator_N7FCdr5Service', true],
            'App\\Controller\\ProgrammeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProgrammeController::show' => ['privates', '.service_locator.qhorb3R', 'get_ServiceLocator_Qhorb3RService', true],
            'App\\Controller\\TestController::show1' => ['privates', '.service_locator.aDkPpL7', 'get_ServiceLocator_ADkPpL7Service', true],
            'App\\Controller\\VoyageController::delete' => ['privates', '.service_locator.R3TFjLG', 'get_ServiceLocator_R3TFjLGService', true],
            'App\\Controller\\VoyageController::edit' => ['privates', '.service_locator.R3TFjLG', 'get_ServiceLocator_R3TFjLGService', true],
            'App\\Controller\\VoyageController::index' => ['privates', '.service_locator.aDkPpL7', 'get_ServiceLocator_ADkPpL7Service', true],
            'App\\Controller\\VoyageController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VoyageController::show' => ['privates', '.service_locator.cRw86ao', 'get_ServiceLocator_CRw86aoService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProgrammeController:delete' => ['privates', '.service_locator.Xvt.gnO', 'get_ServiceLocator_Xvt_GnOService', true],
            'App\\Controller\\ProgrammeController:edit' => ['privates', '.service_locator.Xvt.gnO', 'get_ServiceLocator_Xvt_GnOService', true],
            'App\\Controller\\ProgrammeController:index' => ['privates', '.service_locator.n7FCdr5', 'get_ServiceLocator_N7FCdr5Service', true],
            'App\\Controller\\ProgrammeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProgrammeController:show' => ['privates', '.service_locator.qhorb3R', 'get_ServiceLocator_Qhorb3RService', true],
            'App\\Controller\\TestController:show1' => ['privates', '.service_locator.aDkPpL7', 'get_ServiceLocator_ADkPpL7Service', true],
            'App\\Controller\\VoyageController:delete' => ['privates', '.service_locator.R3TFjLG', 'get_ServiceLocator_R3TFjLGService', true],
            'App\\Controller\\VoyageController:edit' => ['privates', '.service_locator.R3TFjLG', 'get_ServiceLocator_R3TFjLGService', true],
            'App\\Controller\\VoyageController:index' => ['privates', '.service_locator.aDkPpL7', 'get_ServiceLocator_ADkPpL7Service', true],
            'App\\Controller\\VoyageController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VoyageController:show' => ['privates', '.service_locator.cRw86ao', 'get_ServiceLocator_CRw86aoService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProgrammeController::delete' => '?',
            'App\\Controller\\ProgrammeController::edit' => '?',
            'App\\Controller\\ProgrammeController::index' => '?',
            'App\\Controller\\ProgrammeController::new' => '?',
            'App\\Controller\\ProgrammeController::show' => '?',
            'App\\Controller\\TestController::show1' => '?',
            'App\\Controller\\VoyageController::delete' => '?',
            'App\\Controller\\VoyageController::edit' => '?',
            'App\\Controller\\VoyageController::index' => '?',
            'App\\Controller\\VoyageController::new' => '?',
            'App\\Controller\\VoyageController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProgrammeController:delete' => '?',
            'App\\Controller\\ProgrammeController:edit' => '?',
            'App\\Controller\\ProgrammeController:index' => '?',
            'App\\Controller\\ProgrammeController:new' => '?',
            'App\\Controller\\ProgrammeController:show' => '?',
            'App\\Controller\\TestController:show1' => '?',
            'App\\Controller\\VoyageController:delete' => '?',
            'App\\Controller\\VoyageController:edit' => '?',
            'App\\Controller\\VoyageController:index' => '?',
            'App\\Controller\\VoyageController:new' => '?',
            'App\\Controller\\VoyageController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
