<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2X3XfC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2X3XfC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2X3XfC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2X3XfC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2X3XfC\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2X3XfC',
    'container.build_id' => '7c8a6b0a',
    'container.build_time' => 1709600623,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2X3XfC');
