<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMIBx7Ol\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMIBx7Ol/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMIBx7Ol.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMIBx7Ol\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMIBx7Ol\App_KernelDevDebugContainer([
    'container.build_hash' => 'MIBx7Ol',
    'container.build_id' => 'aa1bcaf1',
    'container.build_time' => 1708383129,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMIBx7Ol');
