<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_billet_index' => [[], ['_controller' => 'App\\Controller\\BilletController::index'], [], [['text', '/billet/']], [], [], []],
    'app_billet_new' => [[], ['_controller' => 'App\\Controller\\BilletController::new'], [], [['text', '/billet/new']], [], [], []],
    'app_billet_show' => [['id'], ['_controller' => 'App\\Controller\\BilletController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/billet']], [], [], []],
    'app_billet_edit' => [['id'], ['_controller' => 'App\\Controller\\BilletController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/billet']], [], [], []],
    'app_billet_delete' => [['id'], ['_controller' => 'App\\Controller\\BilletController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/billet']], [], [], []],
    'app_evenement_index' => [[], ['_controller' => 'App\\Controller\\EvenementController::index'], [], [['text', '/evenement/']], [], [], []],
    'app_evenement_new' => [[], ['_controller' => 'App\\Controller\\EvenementController::new'], [], [['text', '/evenement/new']], [], [], []],
    'app_evenement_show' => [['id'], ['_controller' => 'App\\Controller\\EvenementController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/evenement']], [], [], []],
    'app_evenement_edit' => [['id'], ['_controller' => 'App\\Controller\\EvenementController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/evenement']], [], [], []],
    'app_evenement_delete' => [['id'], ['_controller' => 'App\\Controller\\EvenementController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/evenement']], [], [], []],
    'app_evenement_eventfront' => [[], ['_controller' => 'App\\Controller\\EvenementController::eventfront'], [], [['text', '/evenement/front/office']], [], [], []],
    'App\Controller\BilletController::index' => [[], ['_controller' => 'App\\Controller\\BilletController::index'], [], [['text', '/billet/']], [], [], []],
    'App\Controller\BilletController::new' => [[], ['_controller' => 'App\\Controller\\BilletController::new'], [], [['text', '/billet/new']], [], [], []],
    'App\Controller\BilletController::show' => [['id'], ['_controller' => 'App\\Controller\\BilletController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/billet']], [], [], []],
    'App\Controller\BilletController::edit' => [['id'], ['_controller' => 'App\\Controller\\BilletController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/billet']], [], [], []],
    'App\Controller\BilletController::delete' => [['id'], ['_controller' => 'App\\Controller\\BilletController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/billet']], [], [], []],
    'App\Controller\EvenementController::index' => [[], ['_controller' => 'App\\Controller\\EvenementController::index'], [], [['text', '/evenement/']], [], [], []],
    'App\Controller\EvenementController::new' => [[], ['_controller' => 'App\\Controller\\EvenementController::new'], [], [['text', '/evenement/new']], [], [], []],
    'App\Controller\EvenementController::show' => [['id'], ['_controller' => 'App\\Controller\\EvenementController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/evenement']], [], [], []],
    'App\Controller\EvenementController::edit' => [['id'], ['_controller' => 'App\\Controller\\EvenementController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/evenement']], [], [], []],
    'App\Controller\EvenementController::delete' => [['id'], ['_controller' => 'App\\Controller\\EvenementController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/evenement']], [], [], []],
    'App\Controller\EvenementController::eventfront' => [[], ['_controller' => 'App\\Controller\\EvenementController::eventfront'], [], [['text', '/evenement/front/office']], [], [], []],
];
