<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_programme_index' => [[], ['_controller' => 'App\\Controller\\ProgrammeController::index'], [], [['text', '/programme/']], [], [], []],
    'app_programme_new' => [[], ['_controller' => 'App\\Controller\\ProgrammeController::new'], [], [['text', '/programme/new']], [], [], []],
    'app_programme_show' => [['id'], ['_controller' => 'App\\Controller\\ProgrammeController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/programme']], [], [], []],
    'app_programme_edit' => [['id'], ['_controller' => 'App\\Controller\\ProgrammeController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/programme']], [], [], []],
    'app_programme_delete' => [['id'], ['_controller' => 'App\\Controller\\ProgrammeController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/programme']], [], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\TestController::show1'], [], [['text', '/test']], [], [], []],
    'app_voyage_index' => [[], ['_controller' => 'App\\Controller\\VoyageController::index'], [], [['text', '/voyage/']], [], [], []],
    'app_voyage_new' => [[], ['_controller' => 'App\\Controller\\VoyageController::new'], [], [['text', '/voyage/new']], [], [], []],
    'app_voyage_show' => [['id'], ['_controller' => 'App\\Controller\\VoyageController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voyage']], [], [], []],
    'app_voyage_edit' => [['id'], ['_controller' => 'App\\Controller\\VoyageController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/voyage']], [], [], []],
    'app_voyage_delete' => [['id'], ['_controller' => 'App\\Controller\\VoyageController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voyage']], [], [], []],
    'App\Controller\ProgrammeController::index' => [[], ['_controller' => 'App\\Controller\\ProgrammeController::index'], [], [['text', '/programme/']], [], [], []],
    'App\Controller\ProgrammeController::new' => [[], ['_controller' => 'App\\Controller\\ProgrammeController::new'], [], [['text', '/programme/new']], [], [], []],
    'App\Controller\ProgrammeController::show' => [['id'], ['_controller' => 'App\\Controller\\ProgrammeController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/programme']], [], [], []],
    'App\Controller\ProgrammeController::edit' => [['id'], ['_controller' => 'App\\Controller\\ProgrammeController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/programme']], [], [], []],
    'App\Controller\ProgrammeController::delete' => [['id'], ['_controller' => 'App\\Controller\\ProgrammeController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/programme']], [], [], []],
    'App\Controller\TestController::index' => [[], ['_controller' => 'App\\Controller\\TestController::show1'], [], [['text', '/test']], [], [], []],
    'App\Controller\VoyageController::index' => [[], ['_controller' => 'App\\Controller\\VoyageController::index'], [], [['text', '/voyage/']], [], [], []],
    'App\Controller\VoyageController::new' => [[], ['_controller' => 'App\\Controller\\VoyageController::new'], [], [['text', '/voyage/new']], [], [], []],
    'App\Controller\VoyageController::show' => [['id'], ['_controller' => 'App\\Controller\\VoyageController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voyage']], [], [], []],
    'App\Controller\VoyageController::edit' => [['id'], ['_controller' => 'App\\Controller\\VoyageController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/voyage']], [], [], []],
    'App\Controller\VoyageController::delete' => [['id'], ['_controller' => 'App\\Controller\\VoyageController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voyage']], [], [], []],
];
